os: linux
dist: debian
language: cpp
services:
    - docker
env:
    global:
    jobs:
        - SCRIPT="build_clang6_Debug_address"
        - SCRIPT="build_clang6_Debug_thread"
        - SCRIPT="build_clang6_Debug_undefined"
        - SCRIPT="build_clang6_Profile_none"
        - SCRIPT="build_clang6_Release_none"
        - SCRIPT="build_clang6_Relwithdebinfo_none"
        - SCRIPT="build_gcc8_Debug_address"
        - SCRIPT="build_gcc8_Debug_thread"
        - SCRIPT="build_gcc8_Debug_undefined"
        - SCRIPT="build_gcc8_Profile_none"
        - SCRIPT="build_gcc8_Release_none"
        - SCRIPT="build_gcc8_Relwithdebinfo_none"

script:
    - docker build -t logate-sdk --cache-from baszerr/logate-sdk docker/sdk/
    - >
        docker run
        --rm
        --cap-add=SYS_PTRACE
        --volume $(pwd):/mnt
        logate-sdk
        /mnt/ci/"${SCRIPT}"
