#!/bin/bash
set -e
DIR=$(dirname "$(readlink -e "$0")")
mkdir -p "build/clang6/Debug/address" \
exec docker run \
       -u "$(id -u):$(id -g)" \
       -v "$DIR:/mnt/prj" \
       -w "/mnt/prj/build/clang6/Debug/address" \
       --cap-add SYS_PTRACE \
       -it \
       --rm \
       --network=host \
       "baszerr/logate-sdk" \
       "$@"
