#!/bin/bash
set -e

function print_usage()
{
    cat <<EOF
This script prepares RPM package of cursate

Options:
    --tag       docker tag of cursate to package
    --help      this message
EOF
}

# Assume this script is in <logate repo>/scripts/
SCRIPT_DIR="$(dirname "$(readlink -f  "${BASH_SOURCE[0]}")")"
REPO_ROOT="$(readlink -f "${SCRIPT_DIR}/../")"

TAG="$(docker image ls | grep '^cursate\>' | head -1 | awk '{ print $2 }')"
VERSION_BASE=0.1

while [ "${1##-}" != "${1}" ]
do
    case "${1}" in
        --tag|-t)
            TAG="${2}"
            shift
        ;;
        --help|-h)
            print_usage
            exit 1
        ;;
    esac
    shift
done


BUILD_DIR="${REPO_ROOT}/build/rpmbuild"
mkdir -p "${BUILD_DIR}"/{BUILD,RPMS/noarch,SOURCES,SPECS,SRPMS} && cd "${BUILD_DIR}"
ln -s -f "${REPO_ROOT}/scripts/logate.spec" "SPECS/logate.spec"

NUMBER_FROM_TAG=${TAG##*-}
NUMBER_FROM_TAG=${NUMBER_FROM_TAG:-0}

VERSION="${VERSION_BASE}.${NUMBER_FROM_TAG}"
export VERSION
RELEASE=$(( "$(ls "${BUILD_DIR}/RPMS/noarch/pas-cursate-${VERSION}"* | wc -l)" + 1 ))
export RELEASE
DOCKER_TAG="${TAG}"
export DOCKER_TAG
export REPO_ROOT

rpmbuild -v --build-in-place --target noarch --define="_topdir ${BUILD_DIR}" -bb "SPECS/logate.spec"
