#!/usr/bin/env python3
import os
import sys
import time
import json

delay = float(sys.argv[1])

while True:
    log = { 'date': time.time(), 'uname': str(os.uname()) }
    sys.stdout.write( json.dumps(log) + "\n" )
    if delay > 0:
        time.sleep(delay)
        sys.stdout.flush()

