#!/bin/bash
set -e
app=$(basename "$0")
app_dir=$(dirname "$(readlink -e "$0")")
root_dir="$app_dir/.."
cd "$root_dir"

runs=0
failed=()

# default toolchains with all modes and sanitizers
for sdk in gcc clang
do
  for mode in Debug Release Profile Relwithdebinfo
  do
    for san in none address thread undefined
    do
      ((++runs))
      echo "$app: #$runs BUILD WITH SDK $sdk MODE $mode SANITIZER $san"
      time ./sdk ./ci/build "$sdk" "$mode" "$san" || failed+=("$sdk $mode $san")
    done
  done
done

# summary
if [ "${#failed[@]}" -gt 0 ]
then
  echo "$0: found ${#failed[@]} errors in total of $runs configurations:"
  for cfg in "${failed[@]}"
  do
    echo -e "\t$cfg"
  done
  exit 1
else
  echo "$0: total of $runs runs - all successful"
  exit 0
fi
